apiVersion: v1
kind: Service
metadata:
  name: current-game
  namespace: website
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
